1.6.2 Update repo deployment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,6 +10,8 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
+    permissions:
+      deployments: write
 
     steps:
       - name: Checkout 🛎️
@@ -23,7 +25,10 @@ jobs:
             -H "Accept: application/vnd.github+json" \
             "https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments" \
             -d "{\"ref\":\"${GITHUB_SHA}\",\"environment\":\"production\",\"auto_merge\":false,\"required_contexts\":[]}")
-          echo "id=$(echo "$response" | jq -r '.id')" >> "$GITHUB_OUTPUT"
+          echo "$response"
+          id=$(echo "$response" | jq -r '.id')
+          [ "$id" = "null" ] && echo "Failed to create deployment" && exit 1
+          echo "id=$id" >> "$GITHUB_OUTPUT"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
